#!/bin/bash

# postinst script for the QwebIRC Debian package.
# By: The Doctor [412/724/301/703][ZS] <drwho@virtadpt.net>
# For: ByzPi (http://project-byzantium.org/)
# License: GPLv3

# Terminate on all errors.
set -e

# The command line options passed to this script are passed by the dpkg
# utility whenever it's installed or deleted.
case "$1" in
    configure)
        echo "Adding unprivileged user account for QwebIRC server." 1>&2
        adduser --system --group --quiet --home /opt/qwebirc --no-create-home \
            --disabled-login qwebirc

        echo "Creating logfile for QwebIRC server." 1>&2
        touch /opt/qwebirc/twisted.log
        chown qwebirc /opt/qwebirc/twisted.log
        ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        echo "Deleting Twisted logfile so the directory can be removed." 1>&2
        rm -f /opt/qwebirc/twisted.log
        ;;

    *)
        echo "Unknown command line argument $1 passed to $0." 1>&2
        exit 1
        ;;
esac

# Clean up after ourselves.
exit 0
