#!/bin/bash

# postinst script for the QwebIRC Debian package.
# By: The Doctor [412/724/301/703][ZS] <drwho@virtadpt.net>
# For: ByzPi (http://project-byzantium.org/)
# License: GPLv3

# Terminate on all errors.
set -e

# The command line options passed to this script are passed by the dpkg
# utility whenever it's installed or deleted.
case "$1" in
    configure)
        echo "Adding unprivileged user account for QwebIRC server." 1>&2
        adduser --system --group --quiet --home /opt/qwebirc --no-create-home \
            --disabled-login qwebirc

        echo "Creating logfile for QwebIRC server." 1>&2
        touch /opt/qwebirc/twistd.log
        chown qwebirc.qwebirc /opt/qwebirc/twistd.log

	echo "Setting permissions on fiddly little files that QwebIRC needs." \
	    1>&2
        chown qwebirc.qwebirc /opt/qwebirc/
        chown qwebirc.qwebirc /opt/qwebirc/.compiled

        echo "Installing initscript for QwebIRC server." 1>&2
        update-rc.d qwebirc defaults
        ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        echo "Deactivating QwebIRC server." 1>&2
        service qwebirc stop

        echo "Deleting Twisted logfile so the directory can be removed." 1>&2
        rm -f /opt/qwebirc/twistd.log

        echo "Disabling QwebIRC server." 1>&2
        update-rc.d -f qwebirc remove
        ;;

    *)
        echo "Unknown command line argument $1 passed to $0." 1>&2
        exit 1
        ;;
esac

# Clean up after ourselves.
exit 0
