#!/bin/bash

# postinst script for the groundstation Debian package.
# By: The Doctor [412/724/301/703][ZS] <drwho@virtadpt.net>
# For: ByzPi (http://project-byzantium.org/)
# License: GPLv3

# Terminate on all errors.
set -e

# The command line options passed to this script are passed by the dpkg
# utility whenever it's installed or deleted.
case "$1" in
    configure)
        echo "Adding unprivileged user account for groundstation" 1>&2
        adduser --system --group --quiet --home /opt/groundstation \
            --no-create-home --disabled-login groundstation

        echo "Creating logfiles for groundstation." 1>&2
        mkdir -p /var/log/groundstation
        chown groundstation.groundstation /var/log/groundstation

        echo "Installing initscript for groundstation." 1>&2
        update-rc.d groundstation defaults
        ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        echo "Stopping groundstation." 1>&2
        service groundstation stop

        echo "Deleting log directory so the directory can be removed." 1>&2
        rm -f /var/log/groundstation

        echo "Removing groundstation from the list of system services." 1>&2
        update-rc.d -f groundstation remove
        ;;

    *)
        echo "Unknown command line argument $1 passed to $0." 1>&2
        exit 1
        ;;
esac

# Clean up after ourselves.
exit 0
